# fly.toml app configuration file generated for port02-long-meadow-3957 on 2024-01-09T17:40:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "port02-long-meadow-3957"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
